// All 92 questions in English and Spanish
export interface Question {
  id: number;
  en: string;
  es: string;
}

export const questions: Question[] = [
  // DISC Questions (1–20)
  // D: 1–5
  { id: 1, en: "I am assertive, demanding, and decisive.", es: "Soy asertivo, exigente y decidido." },
  { id: 2, en: "I enjoy doing multiple tasks at once.", es: "Disfruto hacer múltiples tareas a la vez." },
  { id: 3, en: "I thrive in a challenge-based environment.", es: "Yo próspero en un entorno impulsado por desafíos" },
  { id: 4, en: "I think about tasks above others or myself.", es: "Pienso en las tareas por encima de los demás o de mí mismo." },
  { id: 5, en: "I am motivated by accomplishment and authority.", es: "Me motiva el logro y la autoridad." },
  // I: 6–10
  { id: 6, en: "I enjoy influencing and inspiring people.", es: "Disfruto influenciar e inspirar a las personas." },
  { id: 7, en: "I am optimistic about others.", es: "Soy optimista acerca de los demás." },
  { id: 8, en: "I tend to be the life of the party.", es: "Tiendo a ser el alma de la fiesta." },
  { id: 9, en: "I think about motivating people.", es: "Pienso en motivar a las personas." },
  { id: 10, en: "I am motivated by recognition and approval.", es: "Me motiva el reconocimiento y la aprobación." },
  // S: 11–15
  { id: 11, en: "I thrive in consistent environments over changing ones.", es: "Prospero en ambientes estables, más que en los cambiantes." },
  { id: 12, en: "I prefer specifics over generalizations.", es: "Prefiero lo específico sobre las generalizaciones." },
  { id: 13, en: "I enjoy small groups of people.", es: "Disfruto los grupos pequeños de personas." },
  { id: 14, en: "I prefer being a member of a team over leading the team.", es: "Prefiero ser miembro de un equipo sobre liderar el equipo." },
  { id: 15, en: "I am motivated by stability and support.", es: "Me motiva la estabilidad y el apoyo." },
  // C: 16–20
  { id: 16, en: "I typically do not take big risks.", es: "Típicamente no tomo grandes riesgos." },
  { id: 17, en: "I love tasks, order and details.", es: "Amo las tareas, el orden y los detalles." },
  { id: 18, en: "I am right most of the time.", es: "Tengo la razón la mayoría del tiempo" },
  { id: 19, en: "I comply with clearly defined rules.", es: "Cumplo con reglas claramente definidas." },
  { id: 20, en: "I am motivated by quality and correctness.", es: "Me motiva la calidad y la corrección." },

  // Spiritual Gift Questions (21–92)
  { id: 21, en: "I like organizing services and events.", es: "Me gusta organizar servicios y eventos." },
  { id: 22, en: "I enjoy starting new churches.", es: "Disfruto iniciar nuevas iglesias." },
  { id: 23, en: "I enjoy working with my hands.", es: "Disfruto trabajar con mis manos." },
  { id: 24, en: "I can tell when someone is insincere.", es: "Puedo darme cuenta cuando alguien es insincero." },
  { id: 25, en: "I pray for the lost daily.", es: "Oro por los perdidos diariamente." },
  { id: 26, en: "Encouraging others is a high priority in my life.", es: "Animar a otros es una alta prioridad en mi vida." },
  { id: 27, en: "Believing God for our daily needs is important to me.", es: "Creer en Dios para nuestras necesidades diarias es importante para mí." },
  { id: 28, en: "Influencing others for the kingdom of God through finances is extremely important to me.", es: "Influenciar a otros para el reino de Dios a través de las finanzas es extremadamente importante para mí." },
  { id: 29, en: "I look for opportunities to pray for the sick.", es: "Busco oportunidades para orar por los enfermos." },
  { id: 30, en: "I enjoy doing the little things that others do not.", es: "Disfruto hacer las pequeñas cosas que otros no hacen." },
  { id: 31, en: "I enjoy having people come to my house.", es: "Disfruto cuando las personas vienen a mi casa." },
  { id: 32, en: "I enjoy spending hours in prayer for other people.", es: "Disfruto pasar horas en oración por otras personas." },
  { id: 33, en: "Education is very important to me.", es: "La educación es muy importante para mí." },
  { id: 34, en: "I tend to motivate others to get involved.", es: "Tiendo a motivar a otros a involucrarse." },
  { id: 35, en: "My heart hurts when I see others hurting.", es: "Mi corazón duele cuando veo a otros sufriendo." },
  { id: 36, en: "I believe God will use me to enact His miracles.", es: "Creo que Dios me usará para realizar Sus milagros." },
  { id: 37, en: "I enjoy sharing the gospel with other people groups and nationalities.", es: "Disfruto compartir el evangelio con otros grupos de personas y nacionalidades." },
  { id: 38, en: "I've devoted considerable time to mastering my voice and or instrument.", es: "He dedicado una cantidad considerable de tiempo a dominar mi voz y/o un instrumento." },
  { id: 39, en: "Caring for the hurting is paramount in my eyes.", es: "Cuidar de los que sufren es primordial ante mis ojos." },
  { id: 40, en: "The willful sin of others really aggravates me.", es: "El pecado voluntario de otros realmente me molesta." },
  { id: 41, en: "I enjoy serving behind the scenes.", es: "Disfruto sirviendo tras bastidores." },
  { id: 42, en: "I enjoy creating outlines of the Bible.", es: "Disfruto creando bosquejos bíblicos." },
  { id: 43, en: "God has used me to interpret a heavenly language.", es: "Dios me ha usado para interpretar un lenguaje celestial." },
  { id: 44, en: "I enjoy the book of Proverbs more than any other book in the Bible.", es: "Disfruto el libro de Proverbios más que cualquier otro libro de la Biblia." },

  // Second cycle (45–68)
  { id: 45, en: "I am passionate about managing details.", es: "Me apasiona manejar los detalles." },
  { id: 46, en: "I prefer to pioneer new ministry projects.", es: "Prefiero ser pionero en nuevos proyectos ministeriales." },
  { id: 47, en: "I consider myself a craftsman or craftswoman.", es: "Me considero un artesano o artesana." },
  { id: 48, en: "I sense when situations are spiritually unhealthy.", es: "Percibo cuando las situaciones son espiritualmente insanas." },
  { id: 49, en: "I am greatly concerned about seeing the lost saved.", es: "Me conmueve profundamente ver a los perdidos ser salvados." },
  { id: 50, en: "I try to come across loving and caring.", es: "Trato de ser amoroso y compasivo." },
  { id: 51, en: "Asking God for a list of big things is exciting to me.", es: "Pedirle a Dios una lista de cosas grandes me emociona." },
  { id: 52, en: "I find ways to give offerings above my tithe.", es: "Encuentro maneras de dar ofrendas por encima de mi diezmo." },
  { id: 53, en: "I believe miraculous healing is for this day and age.", es: "Creo que la sanidad milagrosa es para esta época." },
  { id: 54, en: "Helping others is one of my highest achievements.", es: "Ayudar a otros es uno de mis mayores logros." },
  { id: 55, en: "Creating a warm and welcoming home is important to me.", es: "Para mí es importante crear un hogar cálido y acogedor." },
  { id: 56, en: "I am burdened to pray for situations in the world.", es: "Siento la carga de orar por situaciones en el mundo." },
  { id: 57, en: "People seek me out to learn more about the Kingdom of God.", es: "Las personas me buscan para aprender más sobre el Reino de Dios." },
  { id: 58, en: "I prefer to take the lead whenever necessary.", es: "Prefiero tomar el liderazgo cuando sea necesario." },
  { id: 59, en: "I'm very sensitive to sad stories.", es: "Soy muy sensible a las historias tristes." },
  { id: 60, en: "Miracles often happen when I'm nearby.", es: "Los milagros a menudo suceden cuando estoy cerca." },
  { id: 61, en: "Living in another country to benefit the gospel is exciting to me.", es: "Vivir en otro país para beneficiar el evangelio me emociona." },
  { id: 62, en: "I desire to serve the church through worship.", es: "Deseo servir a la iglesia a través de la adoración." },
  { id: 63, en: "I enjoy connecting, caring, and coaching others.", es: "Disfruto conectar, cuidar y entrenar a otros." },
  { id: 64, en: "Confronting someone with sin in their life is not hard.", es: "Confrontar a alguien con pecado en su vida no es difícil." },
  { id: 65, en: "It bothers me when people sit around and do nothing.", es: "Me molesta cuando las personas se sientan y no hacen nada." },
  { id: 66, en: "I share Biblical truth with others in hopes of their personal growth.", es: "Comparto la verdad bíblica con otros con la esperanza de su crecimiento personal." },
  { id: 67, en: "I pray in tongues daily.", es: "Oro en lenguas diariamente." },
  { id: 68, en: "When I study scripture God gives me unique insights.", es: "Cuando estudio las escrituras, Dios me da perspectivas únicas." },

  // Third cycle (69–92)
  { id: 69, en: "Creating a task list is easy and enjoyable for me.", es: "Crear una lista de tareas es fácil y disfrutable para mí." },
  { id: 70, en: "I am attracted to ministries that start new churches.", es: "Me atraen los ministerios que inician nuevas iglesias." },
  { id: 71, en: "Building something with my hands is very rewarding to me.", es: "Construir algo con mis manos es muy gratificante para mí." },
  { id: 72, en: "I can pinpoint issues or problems before others.", es: "Puedo identificar problemas antes que otros." },
  { id: 73, en: "I enjoy sharing the gospel with a total stranger.", es: "Disfruto compartir el evangelio con un total desconocido." },
  { id: 74, en: "I look for ways to be an encouragement to other people.", es: "Busco maneras de ser una fuente de ánimo para otros." },
  { id: 75, en: "I trust that God has my back in every situation.", es: "Confío en que Dios me respalda en cada situación." },
  { id: 76, en: "Making more money means I can give more.", es: "Ganar más dinero significa que puedo dar más." },
  { id: 77, en: "God has used me to bring healing to those who are sick.", es: "Dios me ha usado para traer sanidad a los enfermos." },
  { id: 78, en: "Being a part of the process is fulfilling to me.", es: "Ser parte del proceso es gratificante para mí." },
  { id: 79, en: "I tend to make total strangers feel at home.", es: "Tiendo a hacer que los desconocidos se sientan como en casa." },
  { id: 80, en: "People often describe me as a prayer warrior.", es: "Las personas a menudo me describen como un guerrero de oración." },
  { id: 81, en: "I enjoy knowing biblical details and helping others to understand.", es: "Disfruto conocer detalles bíblicos y ayudar a otros a entender." },
  { id: 82, en: "I delegate responsibilities to accomplish tasks.", es: "Delego responsabilidades para cumplir tareas." },
  { id: 83, en: "I am motivated to help those who are less fortunate.", es: "Me motiva ayudar a los menos afortunados." },
  { id: 84, en: "I have a constant hunger to see God's miraculous power.", es: "Tengo un hambre constante de ver el poder milagroso de Dios." },
  { id: 85, en: "I focus a lot on reaching the world for Christ.", es: "Me enfoco mucho en alcanzar al mundo para Cristo." },
  { id: 86, en: "I gain my deepest satisfaction through leading others in vocal or instrumental worship.", es: "Obtengo mi mayor satisfacción a través de guiar a otros en adoración vocal o instrumental." },
  { id: 87, en: "I enjoy walking with someone in times of distress.", es: "Disfruto caminar con alguien en tiempos de calamidad." },
  { id: 88, en: "I enjoy hearing passionate and clear preaching of the truth.", es: "Disfruto escuchar la predicación apasionada y clara de la verdad." },
  { id: 89, en: "I like to do small things that others pass over.", es: "Me gusta hacer las cosas pequeñas que otros pasan por alto." },
  { id: 90, en: "I prefer to teach the Bible topically rather than verse by verse.", es: "Prefiero enseñar la Biblia por temas en vez de versículo por versículo." },
  { id: 91, en: "Praying in the Spirit is encouraging and important to me.", es: "Orar en el Espíritu es alentador e importante para mí." },
  { id: 92, en: "When faced with difficulty I tend to make wise decisions and choices.", es: "Cuando enfrento dificultades, tiendo a tomar decisiones sabias." },
];
